{{- if and .Values.externalsecret  .Values.externalsecret.name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecret.name }}
spec:
  target:
    creationPolicy: 'Owner'
  data:
    - secretKey: {{ .Values.externalsecret.key }}
      remoteRef:
        key: {{ .Values.externalsecret.remote.key }}
        property: {{ .Values.externalsecret.remote.property }}
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
{{- end -}}
