apiVersion: v2
name: weblate
description: Helm chart for weblate externalsecret support
type: application
version: 0.0.3
appVersion: 0.0.3

dependencies:
- name: weblate
  version: 0.4.31
  repository: https://helm.weblate.org
