apiVersion: v2
name: weblate
description: Helm chart for weblate externalsecret support
type: application
version: 0.0.4
appVersion: 0.0.4

dependencies:
- name: weblate
  version: 0.5.3
  repository: https://helm.weblate.org
