---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecret.name }}
spec:
  target:
    creationPolicy: 'Owner'
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: {{ .Values.externalsecret.key }}
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend