---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ara
  name: {{ include "common.fullname" $ }}-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: ara
  type: ClusterIP
