annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Housekeeping nodeSelector indent
      links:
        - name: GitHub Issue
          url: https://github.com/startechnica/apps/issues/59
  licenses: Apache-2.0
  images: |
    - name: netbox
      image: docker.io/netboxcommunity/netbox:v3.7.3-2.8.0
apiVersion: v2
appVersion: v3.7.3
name: netbox
kubeVersion: ">=1.25.0"
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
home: https://github.com/startechnica/apps/tree/main/charts/netbox
icon: https://raw.githubusercontent.com/netbox-community/netbox/develop/docs/netbox_logo.png
maintainers:
- name: Firmansyah Nainggolan
  email: firmansyah@nainggolan.id
  url: https://firmansyah.nainggolan.id
dependencies:
- name: postgresql
  version: 13.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
- name: redis
  version: 18.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
  tags:
    - bitnami-common
  alias: bitnami-common
- name: st-common
  repository: https://startechnica.github.io/apps
  version: 0.x.x
  alias: startechnica-common
keywords:
  - ipam
  - netbox
type: application
version: 5.0.7