apiVersion: v2
name: eso-clustersecretstore
description: Helm chart for eso ClusterSecretStore
type: application
version: 0.1.2
appVersion: 0.1.2

dependencies:
- name: external-secrets
  alias: external-secrets-operator
  version: 0.9.9
  repository: https://charts.external-secrets.io
