{{- range .Values.vaults }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
  provider:
    vault:
      server: {{ .vault.server }}
      path: {{ .vault.path }}
      version: {{ .vault.version }}
      auth:
        # VaultJwt authenticates with Vault using the JWT/OIDC auth mechanism
        # https://www.vaultproject.io/docs/auth/jwt
        jwt:
          # Path where the JWT authentication backend is mounted
          path: {{ .vault.auth.jwt.path }}
          # JWT role configured in a Vault server, optional.
          role: {{ .vault.auth.jwt.role }}
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: {{ .vault.auth.jwt.sa }}
              namespace: {{ .namespace }}
            # `expirationSeconds` defaults to 10 minutes if not supplied
            expirationSeconds: {{ .vault.auth.jwt.expiration }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .vault.auth.jwt.sa }}-auth-delegator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ .vault.auth.jwt.sa }}
  namespace: {{ .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .vault.auth.jwt.sa }}-token
  namespace: {{ .namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .vault.auth.jwt.sa }}
type: kubernetes.io/service-account-token
{{- end }}
