---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecret.azure.name }}
spec:
  data:
    - secretKey: SOCIAL_AUTH_AZUREAD_OAUTH2_KEY
      remoteRef:
        key: {{ .Values.externalsecret.azure.location }}
        property: SOCIAL_AUTH_AZUREAD_OAUTH2_KEY
    - secretKey: SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET
      remoteRef:
        key: {{ .Values.externalsecret.azure.location }}
        property: SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET
  target:
    creationPolicy: 'Owner'
    template:
      metadata:
        labels:
          app.kubernetes.io/name: netbox
          app.kubernetes.io/part-of: netbox
      data:
        azure.py: "
          SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = '{{ .SOCIAL_AUTH_AZUREAD_OAUTH2_KEY }}'\n
          SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = '{{ .SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET }}'\n"
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecret.s3.name }}
spec:
  data:
    - secretKey: AWS_S3_ENDPOINT_URL
      remoteRef:
        key: {{ .Values.externalsecret.s3.location }}
        property: AWS_S3_ENDPOINT_URL
    - secretKey: AWS_S3_REGION_NAME
      remoteRef:
        key: {{ .Values.externalsecret.s3.location }}
        property: AWS_S3_REGION_NAME
    - secretKey: AWS_STORAGE_BUCKET_NAME
      remoteRef:
        key: {{ .Values.externalsecret.s3.location }}
        property: AWS_STORAGE_BUCKET_NAME
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalsecret.s3.location }}
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalsecret.s3.location }}
        property: AWS_SECRET_ACCESS_KEY
  target:
    creationPolicy: 'Owner'
    template:
      metadata:
        labels:
          app.kubernetes.io/name: netbox
          app.kubernetes.io/part-of: netbox
      data:
        s3-config.yaml: "
          STORAGE_CONFIG:\n
            AWS_S3_ENDPOINT_URL: \"{{ .AWS_S3_ENDPOINT_URL }}\"\n
            AWS_S3_REGION_NAME: \"{{ .AWS_S3_REGION_NAME }}\"\n
            AWS_STORAGE_BUCKET_NAME: \"{{ .AWS_STORAGE_BUCKET_NAME }}\"\n
            AWS_ACCESS_KEY_ID: \"{{ .AWS_ACCESS_KEY_ID }}\"\n
            AWS_SECRET_ACCESS_KEY: \"{{ .AWS_SECRET_ACCESS_KEY }}\"\n"
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
