{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecretName) (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-db" (include "netbox.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.externalDatabase.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.externalDatabase.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  db-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-%s" (include "netbox.fullname" .) "external-db") "key" "db-password" "length" 32 "providedValues" (list "externalDatabase.password") "context" $) }}
{{- end }}
